name: APIDOC

on:
  push:
    branches: [ master ]

jobs:
  apidoc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: .
        recurse: true
        output_dir: ./apidoc
