name: APIDOC

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: test
      run: ls

    - name: OpenAPI Diff
      uses: mvegter/openapi-diff-action@v0.1.1
      with:
        spec-file-path: ./coronavirus/apidoc/swagger.json
